version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile  # Path to the Django backend Dockerfile
    ports:
      - "8000:8000"  # Expose Django app on port 8000
#    network_mode: host

  frontend:
    build:
      context: ./frontend/ict-frontend/  # Use the frontend directory as the build context
      dockerfile: Dockerfile  # Path to the React frontend Dockerfile
    ports:
      - "3000:3000"  # Expose React app on port 3000
#    network_mode: host
