# Generated by Django 4.2.7 on 2023-11-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_truck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shavedice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snackbar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
