# Generated by Django 4.2.7 on 2023-11-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_review_purchase_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='purchases',
            field=models.ManyToManyField(to='customers.purchase'),
        ),
    ]
