# Generated by Django 4.2.7 on 2023-11-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_order_items_order_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='total_spent',
        ),
    ]
