# Generated by Django 4.2.7 on 2023-11-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_promotion_payment_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
