# Generated by Django 4.2.7 on 2023-11-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_purchase_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
    ]
